carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove')
]

pernalete_store/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include

from django.conf.urls.static import static
from django.conf import settings

from . import views

from products.views import ProductListView

urlpatterns = [
    path('', ProductListView.as_view(), name = 'index'),
    path('usuarios/login', views.login_view, name = 'login'),
    path('usuarios/logout', views.logout_view, name = 'logout'),
    path('usuarios/registro', views.register, name = 'register'),
    path('admin/', admin.site.urls),
    path('productos/',include('products.urls')),
    path('carrito/',include('carts.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>

    {% include 'navbar.html' %}

    <div class="container">

        {% include 'messages.html' %}
        
        <div class="row mt-3">
            
            {% block content %}
                
            {% endblock content %}
                
        </div>
    </div>
    
</body>
<script src="https://kit.fontawesome.com/ac1fc99a56.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</html>

templates/index.html
{% extends 'base.html' %}


{% block content %}

<div class="col">
    <h4 class="text-center">{{ message }}</h4>
    {% include 'products/snippets/search.html' %}
    {% include 'products/snippets/list.html' %}
    

</div>
    
{% endblock content %}
    

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {%if message.tags == 'success'%}alert-success{%else%}alert-danger{%endif%}">
            <button type="button" class="close" data-dismiss="alert">x</button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
{% url 'login' as login %}
{% url 'register' as register %}
{% url 'logout' as logout %}
{% url 'carts:cart' as cart %}

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <a href="{% url 'index' %}" class="navbar-brand">Pernalete Store</a>

    <button type="button" name="button" class="navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#navb">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navb" class="navbar-collapse collapse hide">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="{{ cart }}" class="nav-link {% if request.path == cart %}active{% endif %}">
                    Mi Carrito <span class="fas fa-shopping-cart"></span>
                </a>
            </li>
        </ul>
        <ul class="nav navbar-nav ml-auto">

            {% if user.is_authenticated %}
                <li class="navbar-item {% if request.path == logout %}active{% endif %}"">
                    <a href=" {{ logout }} " class="nav-link">
                        <span class="fas fa-sign-out-alt"></span>
                        Loguot</a>
                </li>
            {% else %}
                <li class="navbar-item {% if request.path == login %}active{% endif %}">
                    <a href="{{ login }}" class="nav-link">
                        <span class="fas fa-user"></span>
                        Login</a>
                </li>
                <li class="navbar-item {% if request.path == register %}active{% endif %}"">
                    <a href="{{ register }}" class="nav-link">
                        <span class="fas fa-user-plus"></span>
                        Registro</a>
                </li>
            {% endif %}

        </ul>
    </div>

</nav>